### ISSUE TITLE
Select button crashes game when using project outfox's latest steam version (and softlocking after selecting song)

### ISSUE THREAD

**Issue by dude98** [DarkBahamut162/itg3encore#1]
where it crashes: song select screen
how: pressing select opens the "change difficulty" options for a second then immediately crashes the game as if it fails to load something
version: Outfox Steam Playtest (Build 40 i think? 41's not on steam yet)
Edit: version does not matter, crashes on latest non steam playtest too

**Comment by dude98** [comment]
the theme is also starting an endless loop when it gets to the screen after selecting a song, making play impossible.

**Comment by DarkBahamut162** [comment]
I might need a bit more information on that since I seem to be unable to replicate it myself:

Operating System
Game Mode

Additionally, which is optional but would help a great deal, a screenrecording of it would be ideal for me to know where and when exactly it happens.
Another help would be providing the crash logs as some information about that might be mentioned there as well.

**Comment by DarkBahamut162** [comment]
Okay... So...

The "softlocking" mostly happened when the game finished loading the song before the animations are done. I have now fixed that by adding another check and it shouldn't happen anymore.

The "select crash" mostly happened on USB Profiles as either I, the theme or the game couldn't load the usb data correctly. It shouldn't crash anymore as I moved certain stuff around that made that happen.

**Comment by dude98** [comment]
it loaded, but now after beating a song and getting to end results, screen freaks out, breaking theme.
[ProjectOutfox-itg3encore-master.ThemeLua.2023-04-12--18.00.18.log](https://github.com/DarkBahamut162/itg3encore/files/11216011/ProjectOutfox-itg3encore-master.ThemeLua.2023-04-12--18.00.18.log)
timestamp for issue in log: 18:05:18

**Comment by dude98** [comment]
![2023-04-12_181944](https://user-images.githubusercontent.com/13279963/231587672-a0f55b11-2902-41ab-9fc5-9c052c0c9a57.jpg)
![2023-04-12_181953](https://user-images.githubusercontent.com/13279963/231587674-db903cd0-c4f5-47c9-8155-e1c1070cc541.jpg)
i've got screenshots of my game right after clearing 1st stage and after entering 2nd stage song select

**Comment by DarkBahamut162** [comment]
First: Wow, that's pretty much HardwareGore right there. Something like that never ever happened to me.
Second: I somehow couldn't replicate it initially.
Third: I noticed that it loaded stuff from "AdditionalSongs". I never used that feature myself so that might be an indication. But I'll check it tomorrow as I now need some sleep.

**Comment by dude98** [comment]
i use additionalsongs as i have multiple stepmania installs.
i'll try moving my song folders later.

**Comment by DarkBahamut162** [comment]
After trying for hours, I still wasn't able to replicate it on my end.
And I checked on both encore sides (normal & final).

I have two remaining questions as they might be my only lead:
What CPU & GPU do you use?
Does this also occure on other themes? [including the [original theme](https://github.com/JoseVarelaP/itg3-sm5-revival) I used as this ones base?]

**Comment by dude98** [comment]
CPU is an intel i7-4500 at 2.4, GPU is an nvidia 765M, i have 3 monitors if that matters, 
only the ITG themes break, ITG2 breaks on language select, yours breaks on score screen, and original ITG3 breaks on score screen.
i backed out into the attract sequence, and it seems to be the camera's location that's bugged, if that glitches out what you see on the score select.
also, the "USB profiles" attract screen just fixed it, but i bet it'll glitch again if i play a song.
yeah, right after the round cleared screen is when it happens, so something there isn't working right for my end, and idk what.

**Comment by DarkBahamut162** [comment]
I have just found out the reason on why the graphical glitches happen. Don't use GLAD as a Video Renderer.
To make sure you don't have it, do the following:

Enable "Show Stats" [You can do that in ITG3ENCORE by going into "Graphics/Sound Options" and enable it somewhere at the very bottom of that list].
Switch your video renderer to OpenGL. [You might need to switch to OutFox's Soundwaves theme for that as I think you can only find it in the "Experimental Settings". You might need to restart the game for it to be displayed on the stats]

**Comment by dude98** [comment]
yeah, it was GLAD renderer.
i switched it in the preferences ini back to opengl and could go through score eval no issue.
hopefully you can figure out why glad render does that, or the outfox devs do.

**Comment by DarkBahamut162** [comment]
I was able to figure out what was causing that, but I won't be able to figure out why it was doing that.
You might need to put an issue on OutFox's github repository for that as it's no longer my problem anymore.
I'm not potentially stealing issues/points for OutFox's Bughunter Leaderboard if they ever decide on updating that one.
I can potentially handle theme-related issues, but not engine-related ones.
And with that, I think I can close this one since everything else I could do has been fixed already.

**Comment by Scraticus** [comment]
> I was able to figure out what was causing that, but I won't be able to figure out why it was doing that. You might need to put an issue on OutFox's github repository for that as it's no longer my problem anymore. I'm not potentially stealing issues/points for OutFox's Bughunter Leaderboard if they ever decide on updating that one. I can potentially handle theme-related issues, but not engine-related ones. And with that, I think I can close this one since everything else I could do has been fixed already.

This is fixed in 4.19/next alpha V build. was an old 3.x bug that has been around since 2007 ;_;, just updating here in case someone has the issue and hasn't updated OutFox yet
