### ISSUE TITLE
Select Button Screenshot doesn't work at score evaluation, and error at ScreenEndingOkay (whatever that is)

### ISSUE THREAD

**Issue by dude98** [DarkBahamut162/itg3encore#3]
Pressing the red (Select) button to save screenshots at score evaluation doesn't work anymore, meaning i have to hit the "machine screenshot" (print screen) button.

[ProjectOutfox-itg3encore-master.ThemeLua.2023-04-13--19.24.16.log](https://github.com/DarkBahamut162/itg3encore/files/11227074/ProjectOutfox-itg3encore-master.ThemeLua.2023-04-13--19.24.16.log)
timestamp: 19:41:38

i don't know what it actually means, but it showed up when i disabled event mode and played the final song. the final score evaluation also had a black box on top of the song cards in the middle. this error was a pop up i had to hit ignore on, so it's a proper error and not a warning like the infinite actor command things that were happening earlier in the log.

Edit: warnings right before error says it's missing a file, and then lua code errors.

**Comment by DarkBahamut162** [comment]
Several things:
- The black box was me loading in the BannerFrame incorrectly. This has been fixed.
- The error mentioned in the log (about ScreenEndingOkay) was me forgetting that I moved the credits frame somewhere else and that I should've redirected it to that now moved file. This has now been fixed as well.

But what I didn't/couldn't fix was the screenshot thing. It turns out that only the print-key makes the screenshots happen.
I doublechecked on StepMania 5.1 & ITGMania and the sound doesn't even trigger with the select-key over there. You might need to create an issue on OutFox's github repository about that since they seem to have tried to fix that and either aren't finished or it broke between updates somewhere (I actually never noticed any of this). It's another engine issue that's beyond my control/understanding.

**Comment by dude98** [comment]
i was using the select button for screenshots just fine when using GLAD renderer (i have screenshots saved in my usb profile's screenshots folder from it)

**Comment by DarkBahamut162** [comment]
If I remember correctly, I mentioned that I was having troubles on loading in USB Profile data correctly. I just checked with both video renderer and it works on soundwaves but not on mine (but I remember it then working on the base itg3 one).
I'm not sure what I did wrong but I might need to check stuff out there...
