### ISSUE TITLE
Can't display Y&A calculated difficulty

### ISSUE THREAD

**Issue by HaleyHalcyon** [DarkBahamut162/itg3encore#7]
I can't switch the calculated difficulty from DB9 to Y&A. How do I do this? The settings menu only has the option to turn calculated difficulties on and off, not switch between the systems.

**Comment by DarkBahamut162** [comment]
The calculated difficulties system puts 2 values (3 in OutFox) against one another and displays the highest one (while showing their type if they differ from the originally set difficulty rating).
It works similarly to Etterna's MinaCalc system.
It had been implimented this way since it turned out that singular calculation systems still have their own inaccuracies.
Combining them with others at least nullifies certain discrepancies.
And even with the most accurate SPS system (only available on OutFox), sometimes DB9 or Y&A comes through with higher end values.

**Comment by HaleyHalcyon** [comment]
But I don't want to see "the highest value among 2 systems". I want to see the value calculated by my preferred system.

**Comment by DarkBahamut162** [comment]
That is not the original intend of the calculated difficulty system itself. The highest value is the only output of that system.
There is nothing else to choose except for the calculation system itself to be turned on or off.
If multiple systems causes this much confusion, I might have to change/obfuscate the then-to-be-displayed values.

If you truly wish to remain using only the Y&A system, you might have to use/download the themes WAIEI 1/2, where it originated from.
The first one can only be downloaded via third parties and might not work correctly to its full extend.
The second one might need a little bit of fiddling with the code to reactivate the LV20 calculation (which Y&A used in an adjusted fashion).

There is nothing else I can currently do from this position onward.

**Comment by HaleyHalcyon** [comment]
But why?

Different level standards have different level value ranges. It’s like saying Pump It Up is harder than ITG because Pump It Up goes up to 27.

**Comment by DarkBahamut162** [comment]
Because it is:
For one: Difficulties get adjusted by their arrow amounts in the calculation (Dance = *1 | PIU = *1.25 => arrows/4 | doubles are seen as singles)
Also: High-level PIU charts are more Bracket/Jump-heavy, making it that much harder if the same chart was played on ITG.
The only major adjustment was made to BeatMania, as they just get halved in total because of the LV12 "threshold".

And finally: If the stepchart is inconsistent, you won't get accurate calculations on regular StepMania.
If you play a 10 for one half and a 20 on the other, the calculation might give you a 13. (lower average)
My SPS system had been created to remedy it and would then give you a 18 for it. (higher average)

**Comment by HaleyHalcyon** [comment]
> Difficulties get adjusted by their arrow amounts in the calculation (Dance = *1 | PIU = *1.25 => arrows/4 | doubles are seen as singles)

This doesn't account for the different standards for DDR and ITG (Pre-X DDR).

**Comment by DarkBahamut162** [comment]
It is not my fault that KONAMI changed their rating system on just one game.
X-Scale had been applied since it aligns itself best with the other gamemodes.
I might be able to add another option for the reversion of the *1.5 adjustment for [Dance Mode] only.

**Comment by DarkBahamut162** [comment]
Because of inactivity, this issue is considered closed.

And in the meantime:
- StepCache has been added and can be turned on for SM/ITGM (and with that SPS on difficulty calculation)
- Convertion between DDR/ITG and X-Scale
